<a href="https://colab.research.google.com/github/SanskarKesharwani000/python/blob/main/pandas1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
data=pd.read_csv("https://bit.ly//drinksbycountry")
data.head(20)

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa
5,Antigua & Barbuda,102,128,45,4.9,North America
6,Argentina,193,25,221,8.3,South America
7,Armenia,21,179,11,3.8,Europe
8,Australia,261,72,212,10.4,Oceania
9,Austria,279,75,191,9.7,Europe
10,Azerbaijan,21,46,5,1.3,Europe
11,Bahamas,122,176,51,6.3,North America
12,Bahrain,42,63,7,2.0,Asia
13,Bangladesh,0,0,0,0.0,Asia
14,Barbados,143,173,36,6.3,North America
15,Belarus,142,373,42,14.4,Europe
16,Belgium,295,84,212,10.5,Europe
17,Belize,263,114,8,6.8,North America
18,Benin,34,4,13,1.1,Africa
19,Bhutan,23,0,0,0.4,Asia